# https://www.playframework.com/documentation/latest/Configuration

ixias.db.mysql {
  hostspec.master.readonly      = false
  hostspec.slave.readonly       = true

  # to_do データソース: DataSourceName("ixias.db.mysql://{master|slave}/to_do") から参照される
  to_do {
    username          = "docker"
    password          = "docker"
    driver_class_name = "com.mysql.cj.jdbc.Driver"
    hostspec.master.jdbc_url = "jdbc:mysql://127.0.0.1:33306/to_do"
    hostspec.slave.jdbc_url  = "jdbc:mysql://127.0.0.1:33306/to_do"
  }
}

play.modules.enabled += "modules.DatabaseModule"
